apiVersion: v1
kind: Service
metadata:
  name: upload-service             
  namespace: vercel-system
spec:
  selector:
    app: upload-service            
  ports:
    - port: 4000                   
      targetPort: 4000             
  type: ClusterIP                  