apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: vercel
  labels:
    app: proxy-service
spec:
  selector:
    app: proxy-service
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP